version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bagsbe
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5532:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    environment:
      DATABASE_URL: postgres://user:password@db:5432/bagsbe
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data:
